name: Get Pull Request Number from SHA
description: |
  Get the Pull Request number from the SHA of the commit.
  Outputs contains the Pull Request number.
inputs:
  token:
    description: GitHub Access Token
    required: false
    default: ${{ github.token }}
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - name: Get Pull Request number
      shell: bash
      id: pr
      env:
          GH_TOKEN: ${{ inputs.token }}
      run: |
        echo "SHA: ${{ github.event.pull_request.head.sha || github.sha }}"

        pull_request_number=$(gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository }}/commits/${{ github.event.pull_request.head.sha || github.sha }}/pulls \
          --jq '.[0].number')

        if [ -z "$pull_request_number" ]; then
          echo "No pull requests found"
          exit 1
        fi

        echo "Pull Request number: $pull_request_number"
        echo "pull-request-number=$pull_request_number" >> "$GITHUB_OUTPUT"
outputs:
  number:
    description: Pull Request number.
    value: ${{ steps.pr.outputs.pull-request-number }}
  url:
    description: URL of the Pull Request.
    value: https://github.com/${{ github.repository }}/pull/${{ steps.pr.outputs.pull-request-number }}
